const initState = {
  activeCoin: "EUR",
  fromNumber: null,
  enabledCoins: ["USD", "HKD", "EUR", "CNY", "JPY", "BTC", "ETH"],
  searchKeyword: "",
  lastUpdateTime: 0,
  appSettings: {
    lang: "cn",
    theme: "auto",
  },
  coins: [
    {
      symbol: "USD",
      sign: "$",
      name: "United States Dollar",
      nameCN: "美元",
      countryCode: "US",
      rate: "1",
      type: "fiat",
    },
    {
      symbol: "HKD",
      sign: "$",
      name: "Hong Kong Dollar",
      nameCN: "港币",
      countryCode: "HK",
      rate: "1",
      type: "fiat",
    },
    {
      symbol: "EUR",
      sign: "€",
      name: "Euro",
      nameCN: "欧元",
      countryCode: "EU",
      rate: "1",
      type: "fiat",
    },
    {
      symbol: "CNY",
      sign: "¥",
      name: "Chinese Yuan",
      nameCN: "人民币",
      countryCode: "CN",
      rate: "1",
      type: "fiat",
    },
    {
      symbol: "JPY",
      sign: "¥",
      name: "Japanese Yen",
      nameCN: "日元",
      countryCode: "JP",
      rate: "1",
      type: "fiat",
    },
    {
      symbol: "BTC",
      sign: "",
      name: "Bitcoin",
      nameCN: "比特币",
      countryCode: null,
      rate: "1",
      type: "crypto",
    },
    {
      symbol: "ETH",
      sign: "",
      name: "Ethereum",
      nameCN: "以太币",
      countryCode: null,
      rate: "322.429239",
      type: "crypto",
    },
  ],
};

export default initState;
